name: This action is going to be run a PR is created
on: pull_request
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Log something
              run: echo "Hello world"
        
