name: Test action
on: 
    pull_request:
        branches:
            - 'primer/react-integration-test-*'
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Log something
              run: echo "Hello world"
        
