name: Merge Queue Test
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Log something
          # MDEwOlJlcG9zaXRvcnkxMjE4MTQyMTA primer/react
          uses: octokit/graphql-action@v2.x
          id: get_latest_release
          with:
            query: |
              mutation {
                lockMergeQueue(input: { repositoryId: "R_kgDOKNFQag"}) {
                  headOid
                  headRef
                }
              }
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
