name: Merge Queue Test
on:
  pull_request:
    types: [labeled, unlabeled]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
        - name: Log something
          # MDEwOlJlcG9zaXRvcnkxMjE4MTQyMTA primer/react
          run: |
            gh api graphql -f query='
              mutation {
                lockMergeQueue(input: { repositoryId: "R_kgDOKNFQag"}) {
                  headOid
                  headRef
                }
              }
            '
